const questions = [
    "I have a strong sense of right and wrong.",					
    "I feel empathy towards others.",				
    "I often feel the need to break rules or disobey authority.",					
    "I have been involved in physical fights in the past year."	,				
    "I tend to blame others for my own mistakes.",				
    "I have a history of substance abuse."	,				
    "I find it difficult to control my temper.",					
    "I believe laws are unnecessary and restrict personal freedom."	,				
    "I often feel anxious or paranoid in social situations."		,			
    "I have stolen something in the past year."					,
    "I have a strong support system of family and friends."		,			
    "I have a tendency to manipulate others to get what I want.",					
    "I feel a sense of entitlement."					,
    "I have difficulty maintaining relationships."		,			
    "I have engaged in vandalism or property damage."	,				
    "I often lie or deceive others."					,
    "I have been diagnosed with a mental illness."		,			
    "I have a stable job or source of income."			,		
    "I have trouble expressing my emotions."			,		
    "I have difficulty understanding social cues."		,			
    "I have been physically abused in the past."		,			
    "I have a history of juvenile delinquency."			,		
    "I have a history of sexual misconduct."			,		
    "I have a strong desire for power and control."		,			
    "I struggle with feelings of inadequacy or low self-esteem.",					
    "I have a tendency to manipulate situations to my advantage.",				
    "I have difficulty trusting others."					,
    "I have a history of violent behavior."					,
    "I often feel like I'm above the law.	"				,
    "I have a strong fear of abandonment."					,
    "I have trouble controlling impulsive behaviors."		,		
    "I have been involved in organized crime."				,	
    "I have a history of financial crimes such as fraud or embezzlement.",					
    "I have a history of self-harm or suicidal ideation.	"			,	
    "I have been diagnosed with a personality disorder."				,	
    "I have experienced traumatic events in my past.	"				,
    "I have a history of impulsivity or reckless behavior."				,	
    "I often feel misunderstood by others."					,
    "I have difficulty accepting responsibility for my actions."	,				
    "I have a strong sense of entitlement."					,
    "I have a history of truancy or school disciplinary issues.	",				
    "I have a tendency to seek out risky or thrill-seeking activities.",				
    "I have difficulty regulating my emotions."					,
    "I often feel bored or restless.	"				,
    "I have a history of drug or alcohol addiction.	"			,	
    "I have a history of manipulative or coercive behavior in relationships."
]

export {questions}